# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: xYakuro.ZetCode
PackageVersion: 0.3.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xYakuro/ZetCode/releases/download/v0.3.0/ZetCode-Setup-0.3.0-x64.exe
  InstallerSha256: 4AFD48D1B26A40F929DDD87171FAA766536F3F2D4E49D7689915467F323C09F5
- Architecture: arm64
  InstallerUrl: https://github.com/xYakuro/ZetCode/releases/download/v0.3.0/ZetCode-Setup-0.3.0-arm64.exe
  InstallerSha256: A1E861BE7BDED3279165614524BC10E24DF78500C6B2B166DE41D6571074E359
ManifestType: installer
ManifestVersion: 1.9.0
