# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: xYakuro.ZetCode
PackageVersion: 0.4.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xYakuro/ZetCode/releases/download/v0.4.0/ZetCode-Setup-0.4.0-x64.exe
  InstallerSha256: 7AA5D863B4C4A653B5E9E3CBF02984F73D767DED37E6CEC6DBD481BCE179D122
- Architecture: arm64
  InstallerUrl: https://github.com/xYakuro/ZetCode/releases/download/v0.4.0/ZetCode-Setup-0.4.0-arm64.exe
  InstallerSha256: D00A2E12F26178287171BF793F521A7108445F616D0BA48B836783E06E05A74E
ManifestType: installer
ManifestVersion: 1.9.0
